"""Generate the listing subject constraint from the application's Course enum."""

from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from courses import Course


def render_migration() -> str:
    values = ",\n".join("        '" + course.value.replace("'", "''") + "'" for course in Course)
    return f"""-- Generated by scripts/generate_subject_migration.py from courses.Course.
-- Existing subjects must already be exact Course values. If validation fails,
-- the transaction rolls back; correct those rows explicitly and run again.
BEGIN;

ALTER TABLE public.listings
    DROP CONSTRAINT IF EXISTS listings_subject_course_check;

ALTER TABLE public.listings
    ADD CONSTRAINT listings_subject_course_check
    CHECK (subject IS NOT NULL AND subject IN (
{values}
    ));

COMMIT;
"""


if __name__ == "__main__":
    path = ROOT / "migrations" / "20261010_listing_subject_course.sql"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_migration())
    print(path)
